### PR TITLE
Fix clang linux builds#144

### PR DESCRIPTION
**Pull request by tph-thuering**

### CODE REVIEW

**Comment by tph-thuering** [comment]
This moves all new travis-ci builds to the ubuntu 14.04 LTS environment (trusty).

**Comment by tph-thuering** [comment]
Thanks to @sgtbigman for testing this in #144

**Comment by sgtbigman** [comment]
Thanks for the mention, @tph-thuering :)

Probably not a big deal, but would it be worth rebasing this against master to remove the 'Merge' commit, as well as the double 'Check' commits?

**Comment by tph-thuering** [comment]
@sgtbigman I rebased from master, but I had to merge again, if you know why, please explain...
I like the way you think :-)
I could just delete the branch, create it a again with the same name, do the change and push, create the PR and merge, but that is just tooo much work ;-)

**Comment by sgtbigman** [comment]
If you run a `git rebase -i develop`, you should end up with just the 
double 'Check' commits, in which case you can just remove one and 
finish the rebase.

After that, just do a force push to this branch, and you should be good 
to go. :)

Hope that helps.

**Comment by sgtbigman** [comment]
Hey @tph-thuering, any luck with rebasing this on your end? :)

**Comment by dhardy** [comment]
Tobi & I just did this; thanks @sgtbigman!

**Pull request closed without merging**
